runtime: nodejs12
service: default
handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html
  - url: /
    static_dir: www

    # [START runtime]runtime: nodejs8handlers:- url: / static_files: dist/index.html upload: dist/index.html- url: / static_dir: dist# [END runtime]
